print("---------------------Alphabets Diamond--------------------")
print("\n")
print("\t\t\t\tA\t\t\t")
print("\t\t\tA\t\tB\t\t")
print("\t\tA\t\tB\t\tC\t")
print("\tA\t\tB\t\tC\t\tD")
print("\t\tA\t\tB\t\tC\t")
print("\t\t\tA\t\tB\t\t")
print("\t\t\t\tA\t\t\t")
print("\n")
print("----------------------------------------------------------")
