a=int(input("Enter the 1st integer number : "))
b=int(input("Enter the 2nd integer number : "))
c=int(input("Enter the 3rd integer number : "))
l=float(input("Enter the 1st decimal number : "))
m=float(input("Enter the 2nd decimal number : "))
n=float(input("Enter the 3rd decimal number : "))
x=input("Enter the 1st word : ")
y=input("Enter the 2nd word : ")
z=input("Enter the 3rd word : ")
print("\n")
print("Thank you for the inputs!!")
print("Printing Integers...")
print("The Value of 'a' ",type(a)," is : ",a)
print("The Value of 'b' ",type(b)," is : ",b)
print("The Value of 'c' ",type(c)," is : ",c)
print("\n")
print("Printing Decimals...")
print("The Value of 'l' ",type(l)," is : ",l)
print("The Value of 'm' ",type(m)," is : ",m)
print("The Value of 'n' ",type(n)," is : ",n)
print("\n")
print("Printing Words...")
print("The Value of 'x' ",type(x)," is : ",x)
print("The Value of 'y' ",type(y)," is : ",y)
print("The Value of 'z' ",type(z)," is : ",z)
print("\n")
