print("------------------------------")
print("         My Favourite         ")
print("            Colors            ")
print("------------------------------")
print("              Red             ")
print("             Green            ")
print("              Blue            ")
print("             Yellow           ")
print("             Orange           ")
print("------------------------------")
